### PR TITLE
Added hint in the readme

### PR DESCRIPTION
**Pull request by majakudlicka**
So that they know where to start

### CODE REVIEW

**Comment by RhodesPeter** [comment]
Hey @majakudlicka - Is this ready for me to review?

**Comment by majakudlicka** [comment]
Yes please! Just a very minor change.
Relates to #3

**Review by RhodesPeter — APPROVED** [review]
I am happy for you to merge this @majakudlicka 😀

**Comment by majakudlicka** [comment]
Thanks but I don't have access to merge :)

**Comment by RhodesPeter** [comment]
Ok cool yea that makes sense! I will merge now :)

**Pull request merged**
